pool:
  vmImage: 'windows-latest'

variables:
- group: Global

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Example.DocumentDb'
  inputs:
    command: 'build'
    configuration: '$(BuildConfiguration)'
    projects: 'Example.DocumentDb\Example.DocumentDb\Example.DocumentDb.csproj'
